# Generated by Django 6.0.6 on 2026-07-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matching", "0002_registration_fee_chf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_chf",
                    models.PositiveIntegerField(
                        help_text="Whole-CHF deposit amount (mirrors Registration.fee_chf)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HELD", "Held"),
                            ("CAPTURED", "Captured"),
                            ("REFUNDED", "Refunded"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        default="HELD",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESSFUL_MATCH", "Successful match"),
                            ("USER_CANCELLED", "User cancelled"),
                            ("SEASON_END_NO_MATCH", "Season end, no match"),
                            ("POST_ACCEPT_NOSHOW", "Post-accept no-show"),
                        ],
                        help_text="Set only on the terminal transition; blank while HELD.",
                        max_length=32,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_refund_id", models.CharField(blank=True, max_length=255)),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The registration this deposit belongs to. SET_NULL so the audit row survives account deletion (VERB-88).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="matching.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
