# Generated by Django 6.0.6 on 2026-07-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("matching", "0002_registration_fee_chf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_chf",
                    models.PositiveIntegerField(
                        help_text="Whole-CHF tip amount (domain never sees centimes)."
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Optional 'say something nice' message from the tipper. Staff-only.",
                        max_length=280,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("REFUNDED", "Refunded")],
                        default="PAID",
                        max_length=16,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_refund_id", models.CharField(blank=True, max_length=255)),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        help_text="The registration this tip belongs to. SET_NULL so the audit row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips",
                        to="matching.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
