# Generated by Django 6.0.6 on 2026-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_tip"),
        ("matching", "0002_registration_fee_chf"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_payment_intent_id", ""), _negated=True),
                fields=("stripe_payment_intent_id",),
                name="unique_tip_stripe_payment_intent_id",
            ),
        ),
    ]
