# Generated by Django 6.0.8 on 2026-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_tip_unique_tip_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESSFUL_MATCH", "Successful match"),
                    ("USER_CANCELLED", "User cancelled"),
                    ("SEASON_END_NO_MATCH", "Season end, no match"),
                    ("POST_ACCEPT_NOSHOW", "Post-accept no-show"),
                    ("STAFF_REFUND", "Refunded by staff in Stripe"),
                ],
                help_text="Set only on the terminal transition; blank while HELD.",
                max_length=32,
            ),
        ),
    ]
