# Generated by Django 6.0.8 on 2026-08-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_payment_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="tip",
            name="stripe_customer_id",
        ),
    ]
