# Generated by Django 6.0.6 on 2026-06-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateTransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        help_text="Primary key of the transitioned model instance."
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field that transitioned (e.g. 'status').",
                        max_length=64,
                    ),
                ),
                (
                    "state_before",
                    models.CharField(
                        help_text="Value of the field immediately before the transition.",
                        max_length=64,
                    ),
                ),
                (
                    "state_after",
                    models.CharField(
                        help_text="Value of the field immediately after the transition.",
                        max_length=64,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Django content type of the transitioned model instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
