# Generated by Django 6.0.6 on 2026-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Raw HTML/plain text as authored by staff."
                    ),
                ),
                (
                    "content_sanitised",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="The nh3-sanitised HTML derived from content, set on save(). Rendered with the |safe filter — never edit directly.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification starts showing; blank means always.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification stops showing; blank means always.",
                        null=True,
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether visitors can dismiss the notification for their browser session. Permanent notifications show no dismiss control.",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("EVERYONE", "Everyone"),
                            ("ANONYMOUS", "Anonymous visitors only"),
                            ("AUTHENTICATED", "Authenticated users only"),
                            ("CUSTOM", "Custom group"),
                        ],
                        default="EVERYONE",
                        max_length=16,
                    ),
                ),
                (
                    "custom_group_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Key into settings.CUSTOM_NOTIFICATION_GROUPS; used only when audience is CUSTOM.",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
