# Generated by Django 6.0.6 on 2026-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-priority", "-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Date-independent kill switch. Uncheck to hide the notification regardless of its display window; it never shows while disabled.",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "Neutral"), (1, "Low"), (2, "Normal"), (3, "High")],
                default=2,
                help_text="Visual priority: sets the strip colour (neutral grey, low blue, normal amber, high red) and sorts higher-priority notices first.",
            ),
        ),
    ]
