# Generated by Django 6.0.6 on 2026-07-07 09:26, then hand-edited (VERB-123)
# to insert the priority -> design/weight data migration between the AddField
# and RemoveField steps. Do not regenerate this file with makemigrations —
# it would drop the RunPython step and silently lose existing rows' priority.

from django.db import migrations, models

# Historical Notification.Priority int -> new design key, per the mapping
# recorded in config/settings/base.py NOTIFICATION_DESIGNS. The Priority
# IntegerChoices class itself is deleted by this change, so the mapping is
# hard-coded here rather than imported from core.models.
PRIORITY_TO_DESIGN = {
    0: "INFO",  # NEUTRAL
    1: "MUTED",  # LOW
    2: "NOTICE",  # NORMAL
    3: "URGENT",  # HIGH
}
DESIGN_TO_PRIORITY = {
    design: priority for priority, design in PRIORITY_TO_DESIGN.items()
}
DEFAULT_PRIORITY = 2  # NORMAL, the old field's default.


def forwards_migrate_priority_to_design_and_weight(apps, schema_editor):
    """Copy each row's old priority into design (mapped) and weight (as-is).

    Preserves current stacking order (weight = old priority int) while
    assigning a settings-backed design key equivalent to the row's old
    visual priority. Uses bulk_update rather than per-row save() — this is a
    schema-migration data step, not model code, so there is no save()
    side-effect (e.g. content sanitisation) to preserve.
    """
    Notification = apps.get_model("core", "Notification")
    rows = list(Notification.objects.all())
    for notification in rows:
        notification.design = PRIORITY_TO_DESIGN.get(
            notification.priority, PRIORITY_TO_DESIGN[DEFAULT_PRIORITY]
        )
        notification.weight = notification.priority
    Notification.objects.bulk_update(rows, ["design", "weight"])


def backwards_migrate_design_and_weight_to_priority(apps, schema_editor):
    """Restore priority from design (inverse mapping), ignoring weight.

    Weight has no equivalent in the old schema, so it is dropped on reverse;
    any design key absent from the inverse mapping (e.g. one added to
    settings after this migration ran) falls back to the old NORMAL default.
    """
    Notification = apps.get_model("core", "Notification")
    rows = list(Notification.objects.all())
    for notification in rows:
        notification.priority = DESIGN_TO_PRIORITY.get(
            notification.design, DEFAULT_PRIORITY
        )
    Notification.objects.bulk_update(rows, ["priority"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_notification_options_notification_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="design",
            field=models.CharField(
                default="NOTICE",
                help_text=(
                    "Key into settings.NOTIFICATION_DESIGNS; drives the strip's "
                    "label, description, and CSS class. No model-level choices "
                    "— validated against settings in the admin form (VERB-123)."
                ),
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="weight",
            field=models.IntegerField(
                default=0,
                help_text=(
                    "Stacking order in the strip: higher weight sorts first, "
                    "independent of design (VERB-123)."
                ),
            ),
        ),
        migrations.RunPython(
            forwards_migrate_priority_to_design_and_weight,
            backwards_migrate_design_and_weight_to_priority,
        ),
        migrations.RemoveField(
            model_name="notification",
            name="priority",
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-weight", "-created_at"]},
        ),
    ]
