# Server-side error monitoring and product analytics (PostHog).
#
# Production-only, server-side exception capture (VERB-65), plus a small set of
# lifecycle product events and page-views (VERB-124). No client-side tracking
# script or cookies are used, so this stays consistent with the cookie policy's
# no-tracking-cookies stance; PostHog is a server-side processor only.
#
# Two coverage paths, both initialised from init_error_monitoring():
#   - Web requests: core.middleware.PostHogExceptionMiddleware calls
#     capture_exception() from process_exception (Django handles request
#     exceptions itself, so they never reach sys.excepthook).
#   - Management commands / crons (expire_matches, run_matching): an uncaught
#     exception propagates to the interpreter excepthook, which PostHog's
#     enable_exception_autocapture hooks.
#
# Product events (VERB-124) are sent via capture_event, a best-effort wrapper
# around posthog.capture mirroring capture_exception's never-raise contract.
# Anonymous visitors (no cookie is ever set) are identified by a salted hash of
# their IP and user-agent (anonymous_distinct_id); once they register, that
# hash and their new user pk are stitched together with alias_identities so
# pre-registration page-views attribute to the resulting person in PostHog.
#
# PII minimisation: email and phone values are redacted from the properties of
# every outbound event by the before_send hook, and local-variable capture is
# disabled so no stack-frame locals (which could hold PII) are ever sent. Event
# properties passed to capture_event must themselves be PII-free by construction
# (role, status, etc.) — the before_send scrub is belt-and-braces, not the
# primary guarantee.

from __future__ import annotations

import hashlib
import logging
import re
from typing import TYPE_CHECKING, Any

import posthog
from decouple import config
from django.conf import settings
from django.http import HttpRequest

from core.geo import get_client_ip

if TYPE_CHECKING:
    # Imported for type-checking only. A runtime import here executes at
    # settings-load time (production.py imports this module), before the app
    # registry is ready, raising AppRegistryNotReady. The `from __future__
    # import annotations` above keeps the annotation a string at runtime.
    from django.contrib.auth.models import User

logger = logging.getLogger(__name__)

# Redaction patterns applied to every string in an outbound event. The phone
# pattern is intentionally broad (a leading + or digit, then 8+ digit/separator
# characters) so partially-formatted numbers are still caught.
_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
_PHONE_RE = re.compile(r"\+?\d[\d\s().\-]{7,}\d")

_EMAIL_PLACEHOLDER = "[email redacted]"
_PHONE_PLACEHOLDER = "[phone redacted]"


def _scrub(value: Any) -> Any:
    """Recursively redact email and phone values from an event payload.

    Walks dicts, lists and strings; leaves other scalar types untouched. Email
    redaction runs before phone redaction so an email is never partly rewritten
    by the (broader) phone pattern.
    """
    if isinstance(value, str):
        redacted = _EMAIL_RE.sub(_EMAIL_PLACEHOLDER, value)
        return _PHONE_RE.sub(_PHONE_PLACEHOLDER, redacted)
    if isinstance(value, dict):
        return {key: _scrub(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_scrub(item) for item in value]
    return value


def scrub_pii(event: Any) -> Any:
    """before_send hook: strip email/phone (Swiss data protection) from events.

    Only the user-controlled ``properties`` sub-dict is scrubbed. The SDK
    message envelope — event name, ``distinct_id``, ``timestamp``, ``uuid`` —
    is generated by PostHog or holds a non-PII identifier (a user pk or a
    salted anonymous hash), and must be left untouched: the broad phone pattern
    would otherwise mangle the ISO-8601 ``timestamp`` (its date and time digit
    runs match the pattern), and PostHog rejects the resulting malformed event
    at ingestion ("missing event name attribute"). Every PII value we could
    emit lives in ``properties`` by construction, so scoping the scrub there
    loses no protection.

    Returns the event so PostHog still sends it; never returns None, so error
    monitoring is not silently disabled by a scrubbing edge case.
    """
    if isinstance(event, dict) and isinstance(event.get("properties"), dict):
        event["properties"] = _scrub(event["properties"])
    return event


def init_error_monitoring() -> bool:
    """Configure PostHog server-side exception capture. No-op without a key.

    Reads ``POSTHOG_API_KEY`` / ``POSTHOG_HOST`` via python-decouple. When the
    key is unset (local dev, CI, or a misconfigured deploy) the function returns
    False and PostHog stays disabled rather than erroring. Returns True when the
    client was configured.
    """
    api_key = config("POSTHOG_API_KEY", default="")
    if not api_key:
        return False

    posthog.api_key = api_key
    posthog.host = config("POSTHOG_HOST", default="https://eu.i.posthog.com")
    posthog.before_send = scrub_pii
    posthog.enable_exception_autocapture = True
    # Never capture stack-frame local variables — they can hold PII (email,
    # phone, names) and are not needed to triage an error (data minimisation).
    posthog.capture_exception_code_variables = False
    posthog.setup()
    logger.info("PostHog error monitoring initialised (host=%s)", posthog.host)
    return True


def capture_exception(exception: BaseException) -> None:
    """Send one exception to PostHog, anonymously (no PII distinct_id).

    Safe to call unconditionally: if monitoring was never initialised (no API
    key) PostHog drops the event, and any failure in the reporting path is
    swallowed so error monitoring never breaks the request it is reporting on.
    """
    try:
        posthog.capture_exception(exception)
    except Exception:  # noqa: BLE001 — monitoring must never raise into the caller.
        logger.warning("Failed to report exception to PostHog", exc_info=True)


def capture_event(
    distinct_id: str, event: str, properties: dict[str, object] | None = None
) -> None:
    """Send one product event to PostHog, best-effort (VERB-124).

    Mirrors ``capture_exception``: safe to call unconditionally. If monitoring
    was never initialised (no API key) PostHog drops the event, and any
    failure in the reporting path is swallowed so analytics never breaks the
    request it is reporting on.

    Args:
        distinct_id: The PostHog identity to attribute the event to — a user
            pk (authenticated) or an anonymous hash (see ``anonymous_distinct_id``).
        event: The event name (e.g. ``"registration"``, ``"match_accepted"``).
        properties: Optional event properties. Must be PII-free by
            construction (the ``before_send`` scrub is belt-and-braces, not
            the primary guarantee) — never pass email or phone here.
    """
    try:
        posthog.capture(
            event, distinct_id=str(distinct_id), properties=properties or {}
        )
    except Exception:  # noqa: BLE001 — analytics must never raise into the caller.
        logger.warning("Failed to send event %r to PostHog", event, exc_info=True)


def anonymous_distinct_id(request: HttpRequest) -> str:
    """Return a stable, cookieless identity hash for an anonymous visitor.

    Computed as ``"anon:" + sha256(salt + ip + user_agent)``, salted with
    ``settings.SECRET_KEY`` so the hash cannot be reversed to recover the raw
    IP. The IP address is read via ``core.geo.get_client_ip`` and stays a local
    variable here — it is never returned or persisted (data minimisation).

    Because no cookie is set, the same visitor produces the same hash only
    while their IP and user-agent are unchanged (e.g. across the registration
    journey in one sitting) — this is a best-effort stitching identity, not a
    durable one.

    Args:
        request: The incoming HTTP request.

    Returns:
        A stable ``"anon:<hex digest>"`` string.
    """
    ip = get_client_ip(request) or ""
    user_agent = request.META.get("HTTP_USER_AGENT", "")
    digest = hashlib.sha256(
        f"{settings.SECRET_KEY}{ip}{user_agent}".encode()
    ).hexdigest()
    # nosemgrep below: the SAST scan's Flask "directly-returned-format-string"
    # XSS rule false-positives here. This is not a Flask view — the value is a
    # PostHog distinct_id, never an HTTP response — and `digest` is a SHA-256
    # hex string with no user-controlled markup, so there is no XSS surface.
    return f"anon:{digest}"  # nosemgrep


def distinct_id_for(request: HttpRequest) -> str:
    """Return the PostHog distinct_id to use for the current request.

    An authenticated user is identified by their ``User.pk``; an anonymous
    visitor by ``anonymous_distinct_id`` (no cookie).

    Args:
        request: The incoming HTTP request.

    Returns:
        The distinct_id string to pass to ``capture_event``.
    """
    if request.user.is_authenticated:
        return str(request.user.pk)
    return anonymous_distinct_id(request)


def alias_identities(request: HttpRequest, user: User) -> None:
    """Stitch an anonymous visitor's identity onto their new user, best-effort.

    Called once, on the anonymous registration success path, so that
    pre-registration page-views (attributed to the anonymous hash) merge into
    the same PostHog person as the resulting user. Mirrors
    ``capture_exception``'s never-raise contract — a failure here must not
    break registration.

    Args:
        request: The request that carried the anonymous visitor's IP/user-agent.
        user: The newly created or reused ``User`` to alias onto.
    """
    try:
        posthog.alias(
            previous_id=anonymous_distinct_id(request), distinct_id=str(user.pk)
        )
    except Exception:  # noqa: BLE001 — analytics must never raise into the caller.
        logger.warning(
            "Failed to alias identities for user pk=%s", user.pk, exc_info=True
        )
