# Generated by Django 6.0.6 on 2026-06-23 11:20

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2026/27", max_length=32, unique=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this season is currently open for registration.",
                    ),
                ),
                (
                    "contact_window_hours",
                    models.PositiveIntegerField(
                        default=72,
                        help_text="Hours a matched pair has to mutually accept before the match is cancelled and both re-queue.",
                    ),
                ),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="PriceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CHILD", "Child"),
                            ("ADULT", "Adult"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Rank within the season; higher means a higher category."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (translated at render time).",
                        max_length=64,
                    ),
                ),
                (
                    "full_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_categories",
                        to="matching.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "code"), name="unique_category_per_season"
                    ),
                    models.UniqueConstraint(
                        fields=("season", "order"), name="unique_order_per_season"
                    ),
                ],
            },
        ),
    ]
