# Generated by Django 6.0.6 on 2026-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="accepted_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of consent statement texts accepted at registration (eligibility declaration first, then T&C). Stored as displayed under the active language at the time of registration.",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tz-aware timestamp at which the participant accepted the statements.",
                null=True,
            ),
        ),
    ]
