# Generated by Django 6.0.6 on 2026-07-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="fee_chf",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Prepaid registration fee in CHF, locked at signup from the REGISTRATION_FEE_TIERS schedule (see matching.pricing_config.fee_chf_for). Frozen — never recomputed against a later tier.",
            ),
        ),
    ]
