# Generated by Django 6.0.6 on 2026-06-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("AMBASSADOR", "Ambassador"), ("REFEREE", "Referee")],
                        max_length=16,
                    ),
                ),
                (
                    "preferred_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VERBIER", "Verbier"),
                            ("THYON", "Thyon"),
                            ("NENDAZ", "Nendaz"),
                            ("VEYSONNAZ", "Veysonnaz"),
                            ("LA_TZOUMAZ", "La Tzoumaz"),
                            ("BRUSON", "Bruson"),
                        ],
                        help_text="Soft preference; used to rank matches, never to gate them.",
                        max_length=16,
                    ),
                ),
                (
                    "held_prior_pass",
                    models.BooleanField(
                        help_text="Prior-season attestation. Ambassadors confirm they held a 4 Vallées pass (True); referees confirm they did not (False)."
                    ),
                ),
                (
                    "discount_eligible",
                    models.BooleanField(
                        default=True,
                        help_text="False for Mont 4 / special-reduction ambassadors, who still supply a valid match but take no discount themselves.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("MATCHED", "Matched"),
                            ("CONFIRMED", "Confirmed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="WAITING",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Queue priority; higher is nearer the front. Adjusted by flaking.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="accounts.account",
                    ),
                ),
                (
                    "price_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="matching.pricecategory",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="matching.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "account"),
                        name="unique_registration_per_season",
                    )
                ],
            },
        ),
    ]
