# Generated by Django 6.0.6 on 2026-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_add_accepted_terms_to_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="ambassador_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tz-aware instant the ambassador accepted; null until they do.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="declined_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tz-aware instant the decline was recorded; null until then.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="declined_by",
            field=models.CharField(
                blank=True,
                choices=[("AMBASSADOR", "Ambassador"), ("REFEREE", "Referee")],
                help_text="Which side declined; empty until a decline occurs.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="no_show_reported_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tz-aware instant the no-show report was filed; null until then.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="no_show_reported_by",
            field=models.CharField(
                blank=True,
                choices=[("AMBASSADOR", "Ambassador"), ("REFEREE", "Referee")],
                help_text="Which side filed the post-accept no-show report; empty until then.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="referee_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tz-aware instant the referee accepted; null until they do.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Proposed"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("ABANDONED", "Abandoned"),
                ],
                default="PROPOSED",
                max_length=16,
            ),
        ),
    ]
