# Generated by Django 6.0.6 on 2026-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0008_registration_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="registration_country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Country name derived from the client IP at registration time (admin-only, never shown to participants). The raw IP is never stored.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="registration_region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Region / subdivision name derived from the client IP at registration time (admin-only, never shown to participants). The raw IP is never stored.",
                max_length=128,
            ),
        ),
    ]
