# Generated by Django 6.0.6 on 2026-07-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_registration_fee_chf"),
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_deposit",
                    models.CharField(
                        choices=[
                            (
                                "NONE",
                                "I would not have registered if there was a deposit",
                            ),
                            ("CHF_5", "CHF 5"),
                            ("CHF_10", "CHF 10"),
                            ("CHF_20", "CHF 20"),
                            ("MORE", "More than CHF 20"),
                        ],
                        help_text="The highest deposit the respondent would have been happy to pay to register.",
                        max_length=16,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        help_text="The registration this response belongs to. SET_NULL so the research row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_response",
                        to="matching.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
