# Generated by Django 6.0.6 on 2026-07-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_registration_fee_chf"),
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_chf_shown",
                    models.PositiveSmallIntegerField(
                        help_text="The hypothetical CHF price point shown to the respondent."
                    ),
                ),
                (
                    "framing_shown",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("FEE", "Fee")],
                        help_text="The wording variant ('deposit' vs 'fee') shown to the respondent.",
                        max_length=16,
                    ),
                ),
                (
                    "q1_answer",
                    models.CharField(
                        choices=[
                            ("DEFINITELY", "Definitely would have registered anyway"),
                            ("PROBABLY", "Probably would have registered anyway"),
                            ("PROBABLY_NOT", "Probably would not have registered"),
                            ("DEFINITELY_NOT", "Definitely would not have registered"),
                        ],
                        help_text="Would the shown price have changed the decision to register?",
                        max_length=16,
                    ),
                ),
                (
                    "q2_answer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEE_AT_REGISTRATION", "Pay at registration"),
                            ("FEE_ON_MATCH_ONLY", "Pay only once matched"),
                            ("WOULD_NOT_PAY", "Would not pay either way"),
                        ],
                        default="",
                        help_text="Optional payment-model preference.",
                        max_length=32,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        blank=True,
                        help_text="The registration this response belongs to. SET_NULL so the research row survives account deletion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_response",
                        to="matching.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
